###### 1. Write Python Programs to use various operators in Python

###### Arithmetic operators


In [1]:
x = 15
y = 4

# Output: x + y = 19
print('x + y =',x+y)

# Output: x - y = 11
print('x - y =',x-y)

# Output: x * y = 60
print('x * y =',x*y)

# Output: x / y = 3.75
print('x / y =',x/y)

# Output: x // y = 3
print('x // y =',x//y)

# Output: x ** y = 50625
print('x ** y =',x**y)


x + y = 19
x - y = 11
x * y = 60
x / y = 3.75
x // y = 3
x ** y = 50625


###### Comparison operators


In [2]:
x = 10
y = 12

# Output: x > y is False
print('x > y is',x>y)

# Output: x < y is True
print('x < y is',x<y)

# Output: x == y is False
print('x == y is',x==y)

# Output: x != y is True
print('x != y is',x!=y)

# Output: x >= y is False
print('x >= y is',x>=y)

# Output: x <= y is True
print('x <= y is',x<=y)


x > y is False
x < y is True
x == y is False
x != y is True
x >= y is False
x <= y is True


###### Logical operators


In [3]:
x = True
y = False

print('x and y is',x and y)

print('x or y is',x or y)

print('not x is',not x)


x and y is False
x or y is True
not x is False


###### Identity operators


In [4]:
x1 = 5
y1 = 5
x2 = 'Hello'
y2 = 'Hello'
x3 = [1,2,3]
y3 = [1,2,3]

# Output: False
print(x1 is not y1)

# Output: True
print(x2 is y2)

# Output: False
print(x3 is y3)


False
True
False


###### Membership operators


In [5]:
x = 'Hello world'
y = {1:'a',2:'b'}

# Output: True
print('H' in x)

# Output: True
print('hello' not in x)

# Output: True
print(1 in y)

# Output: False
print('a' in y)


True
True
True
False


###### 2. Create list of elements and slice and dice it



In [7]:
#my_list[start:end]
x = ["a", "b", "c", "d"]
x[1:3]

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


###### 3. Using while loop accept numbers until sum of numbers is less than 100



In [13]:
mySum = 0 
num = 1 
while num <= 100: 
    mySum += num 
    num += 1    
mySum


5050

###### 4. Write a python program Read & write Excel files 



###### Creating new file

In [15]:
from openpyxl import Workbook
import time

book = Workbook()
sheet = book.active

sheet['A1'] = 56
sheet['A2'] = 43

now = time.strftime("%x")
sheet['A3'] = now

book.save("E:\DA (assignment)\\sample.xlsx")


##### Writing a file

In [19]:
#from openpyxl import Workbook

#book = Workbook()
#sheet = book.active

sheet['A1'] = 1
sheet.cell(row=2, column=2).value = 2

book.save('E:\DA (assignment)\\write2cell.xlsx')


###### Reading a file

In [20]:
import openpyxl

book = openpyxl.load_workbook('E:\DA (assignment)\\sample.xlsx')

sheet = book.active

a1 = sheet['A1']
a2 = sheet['A2']
a3 = sheet.cell(row=3, column=1)

print(a1.value)
print(a2.value) 
print(a3.value)


56
43
03/21/22


###### 6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy



In [29]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


###### 7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array



In [30]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)


Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]
